[workspace]
resolver = "3"
members = [
    "crates/app", "crates/core",
    "crates/decode", "crates/egui",
    "crates/engine", "crates/project", "crates/render",
    "crates/tauri/src-tauri", "crates/transport"
]

[workspace.package]
version = "0.1.0"
edition = "2024"
