[package]
name = "daw_app"
version.workspace = true
edition.workspace = true

[dependencies]
daw_decode = { path = "../decode" }
daw_engine = { path = "../engine" }
daw_project = { path = "../project" }
daw_transport = { path = "../transport" }
gpui = "*"
anyhow = "1.0"
