[package]
name = "daw_app"
version.workspace = true
edition.workspace = true

[dependencies]
daw_core = { path = "../core" }
gpui = "*"
anyhow = "1.0"
rfd = "0.16"
unicode-segmentation = "1.10"
dirs = "6.0.0"
toml = "0.9.8"
serde = { version = "1.0.228", features = ["derive"] }
