[package]
name = "daw_engine"
version.workspace = true
edition.workspace = true

[dependencies]
daw_decode = { path = "../decode" }
daw_transport = { path = "../transport" }
cpal = "0.16"
anyhow = "1.0"
rtrb = "0.3"
